### ISSUE TITLE
Issue with using DeeReCT-TSS: empty output files

### ISSUE THREAD

**Issue by dbeseiso** [JoshuaChou2018/DeeReCT-TSS_release#1]
Hello,

My name is Dana, I am a Ph.D. candidate at the University of Michigan in the United States, and I am contacting you to ask a few questions about DeeReCT-TSS. 

I am interested in using DeeReCT-TSS to identify active TSSs in breast cancer. I am using RNA-seq data from breast cancer tissue from the GEO database (GSM5695914). I aligned the RNA-seq reads to a reference human genome and obtained a BAM file (which is 108 GB). I am using a .bed file for scanning all protein coding regions (generated per instructions on the website + the lung DeeReCT-TSS model. I have also downloaded run.sh and run1thread.sh. In the same directory, I made a folder named src to which I downloaded 05.scan.app.v2.py. From that same directory, I am using the following command:

sbatch ./run.sh \ TSS/mapped/Aligned.sortedByCoord.out.bam \ TSS/gencode.v38.pcg.extups5k.bed \ TSS/DeeReCT-TSS-Models/lung/model_best.npz \ TSS/hg38.fa \ TSS/attempt13 \ 0 \ 25

I have also tried using 1, 5, 10, 50, 100, and 200 threads. 

In all output files I see:
 combined.predicted.cluster (0 Bytes)
 combined.raw.prediction  (0 Bytes)
 ref_data.p (2.99 GB)

I also see the following error message:

"processing bam file TSS/mapped/Aligned.sortedByCoord.out.bam ...
the sequencing data is strandless ...
splitting files 4 parallelization ...
split: invalid number of chunks: ‘’
processing TSS/attempt10-2/RNAseq.depth.part* ...
grep: TSS/attempt10-2/RNAseq.depth.part*: No such file or directory
extracting genomic regions 4 scanning ...

*****
***** ERROR: Requested column 4, but database file TSS/attempt10-2/RNAseq.depth.part*.sorted only has fields 1 - 0.
scanning the genome ...
cleaning tmporary files
clustering the predictions ...
change to 0-based bed format
awk: fatal: cannot open file `TSS/attempt10-2/RNAseq.depth.part*.merged.bedgraph' for reading (No such file or directory)

*****
***** ERROR: Requested column 4, but database file - only has fields 1 - 0.
merging the output cluster ...
cat: 'TSS/attempt10-2/RNAseq.depth.part*.bedgraph': No such file or directory"

Any help in fixing this error to obtain the TSS prediction files is highly appreciated! Please let me know if I can provide any additional information. Thank you very much!

**Comment by JoshuaChou2018** [comment]
Hi, it looks like the problem starts at "split: invalid number of chunks: ‘’", could you share more details of the intermediate result at this step?

**Comment by dbeseiso** [comment]
Hello,

I get this message from an output file after the job is done.

To run DeeReCT-TSS, I am submitting a job to a cluster using the command
"sbatch". When the job is done, it spits out this error message and I
see combined.predicted.cluster
(0 Bytes), combined.raw.prediction  (0 Bytes), and ref_data.p (2.99 GB) in
the output folder. When I try to run DeeReCT-TSS directly (without
submitting a job using sbatch), I don't get any results or error messages
even if I let it run for hours.

Best,
Dana

**Comment by JoshuaChou2018** [comment]
it's really difficult for us to locate your bug with the information you provided, could you please show all detailed outputs and all intermediate results for this step, let's say some screenshots?  "When I try to run DeeReCT-TSS directly (without submitting a job using sbatch), I don't get any results or error messages even if I let it run for hours."

**Comment by dbeseiso** [comment]
Hello!

I ran both commands (using sbatch and bash) and took screenshots of
intermediate files. Please let me know if I can provide any
additional information. Thank you very much!!

Best,
Dana

**Comment by JoshuaChou2018** [comment]
please paste them here

**Comment by christear** [comment]
It looks like the 'split' command didn't work correctly. Can you check whether the threads number you used were passed to the command 'split' ?

**Comment by dbeseiso** [comment]
Hello,

How can I check that? Thank you!

Best,
Dana

**Comment by dbeseiso** [comment]
Attaching screenshots here:
[DeeReCT_TSS_Output_DB.pptx](https://github.com/JoshuaChou2018/DeeReCT-TSS_release/files/12739842/DeeReCT_TSS_Output_DB.pptx)

**Comment by dbeseiso** [comment]
Hello,
I have also tried with 1 thread and found the same files/error in the output folder. Thank you!

**Comment by christear** [comment]
Could you please just directly run this command ?  
split -n l/$thread -d $out_dir/RNAseq.depth.bed $out_dir/RNAseq.depth.part. 
and check whether a series of spliced files are generated ? if the RNAseq.depth.bed is not empty and intact. 
Since this script was written by bash, it can be run step by step.

**Comment by dbeseiso** [comment]
I get: 
_split: invalid number of chunks: ‘’_

**Comment by christear** [comment]
could you please paste you commend here ? I mean this line 'split -n l/$thread -d $out_dir/RNAseq.depth.bed $out_dir/RNAseq.depth.part.'
you can debug as follow:
echo $thread 
or replace the thread with real numbers like:
split -n l/25 -d $out_dir/RNAseq.depth.bed

**Comment by dbeseiso** [comment]
Ok I tried:
_split -n l/25 -d attempt18/RNAseq.depth.bed attempt18/RNAseq.depth.part_

and it worked. RNAseq.depth.part00-24 were generated. Each is 960 MB (they might be small because the RNAseq.depth.bed file is incomplete (23.4 GB) as that run disconnected)

**Comment by dbeseiso** [comment]
How do I proceed? Thank you!

**Comment by christear** [comment]
This means the giving thread parameter did not pass to the script correctly. You can either debug to find the reason or run the rest of code manually (line by line). i.e.
You can proceed with the rest of the code. i.e. run this block of code (paste and run) or run them line by line. 
```bash
for eachp in $out_dir/RNAseq.depth.part*
do
	echo processing $eachp ...
#	date
	bash run1thread.sh $eachp $bed_reg $model $genome $out_dir & 
        # '&' can put the jobs into background. without this, it will run one by one 
	sleep 2s
#	date
done
wait 
# 'wait': waiting for all the jobs done, and then proceed
```

**Comment by yunzhang1998** [comment]
I have the same mistake. The "$depth_bed.merged.bedgraph" file was not generated.

**Comment by yunzhang1998** [comment]
pip install absl-py==1.1.0 ; I have solved the problem.
